### ISSUE TITLE
Artikelfotos hinzufügen

### ISSUE THREAD

**Issue by Paetrick** [Playful-Interactive-Environments/pie-lab.at#32]
Fotos von Artikel über PIE Lab aus Magazinen hinzufügen.
[PhotosArticels.zip](https://github.com/Playful-Interactive-Environments/pie.fh-hagenberg.at/files/983253/PhotosArticels.zip)

**Comment by hochleitner** [comment]
Zeit, alte Issues aufzuarbeiten, ich habe mal über die Fotos drüber geschaut, denke aber, dass sie für die Webseite keinen rechten Mehrwert bringen, weil sie für die Projekte bzw. Events nichts aussagen. Ich schließe das Issue daher mal.
