### ISSUE TITLE
Fotos für InterPLayces

### ISSUE THREAD

**Issue by michaellankes** [Playful-Interactive-Environments/pie-lab.at#35]
Lieber Wolfi,

So, ich hoff, dass ich das jetzt richtig mache. Hab die Bilder erstellt (groß und klein) - ich hab sie auch gleich durchnummeriert - 01 soll ganz vorne hin - dann die bestehenden verwenden - ab 06 wieder die neuen Bilder einfügen.

Grüße,

Michi

![interplayces-01](https://user-images.githubusercontent.com/17197361/49288090-13447b80-f4a0-11e8-8af7-159ee10a55f1.jpg)
![interplayces-01-150](https://user-images.githubusercontent.com/17197361/49288091-13dd1200-f4a0-11e8-9b50-d9232b015436.jpg)
![interplayces-06](https://user-images.githubusercontent.com/17197361/49288092-13dd1200-f4a0-11e8-9867-c6e8a0425bf3.jpg)
![interplayces-06-150](https://user-images.githubusercontent.com/17197361/49288093-13dd1200-f4a0-11e8-8d80-a259c2e60b0f.jpg)
![interplayces-07](https://user-images.githubusercontent.com/17197361/49288094-13dd1200-f4a0-11e8-9e24-60a6d53a847c.jpg)
![interplayces-07-150](https://user-images.githubusercontent.com/17197361/49288095-13dd1200-f4a0-11e8-8e70-a069df00ed22.jpg)
![interplayces-08](https://user-images.githubusercontent.com/17197361/49288097-13dd1200-f4a0-11e8-9747-c35422e4f8af.jpg)
![interplayces-08-150](https://user-images.githubusercontent.com/17197361/49288098-1475a880-f4a0-11e8-8f8a-a5cd251f7811.jpg)

**Comment by hochleitner** [comment]
Okay, lesson learned: files are being renamed when uploaded here. Putting them in a zip-files (or similar) makes sense.
