### ISSUE TITLE
EAT

### ISSUE THREAD

**Issue by GeorgiKostov** [Playful-Interactive-Environments/pie-lab.at#46]
**Name**
HektAR

**Type**
Funded Research Project

**Start date**
2019

**End date**
2021

**Title Image**
![Title Image](https://user-images.githubusercontent.com/17121385/137690921-76771e5d-fb0f-40c7-93db-cdd7088a1380.jpg)

**Screenshots**
![Layer 1](https://user-images.githubusercontent.com/17121385/137690888-1989a9d5-69c3-4b3e-b678-cf5fe2fc4795.jpg)
![Layer 1_thumbnail](https://user-images.githubusercontent.com/17121385/137690892-75691ee8-6f45-400c-9d99-0ca27939c6ea.jpg)
![Layer 2](https://user-images.githubusercontent.com/17121385/137690893-a5f75f6f-ca04-45f7-af62-bbb5c5513ad4.jpg)
![Layer 2_thumbnail](https://user-images.githubusercontent.com/17121385/137690897-98b9fab6-ab64-4f11-8b7f-9f863e20ac96.jpg)
![Layer 3](https://user-images.githubusercontent.com/17121385/137690898-311829c9-7ca6-4df1-9f4b-7ab02879fa0c.jpg)
![Layer 3_thumbnail](https://user-images.githubusercontent.com/17121385/137690900-6010e647-b6d6-4dd4-a175-b690a05b0607.jpg)
![Layer 4](https://user-images.githubusercontent.com/17121385/137690902-8b75a7ab-7454-4b5d-993a-db80ba39c346.jpg)
![Layer 4_thumbnail](https://user-images.githubusercontent.com/17121385/137690905-177ec7be-1962-4d3b-ab3d-ac9fa1bc5515.jpg)
![Layer 5](https://user-images.githubusercontent.com/17121385/137690907-37fbee22-bd05-48dc-9e5b-ac82cc31f6f1.jpg)
![Layer 5_thumbnail](https://user-images.githubusercontent.com/17121385/137690908-cca8f794-182f-4384-bd38-d37c561029f0.jpg)
![Layer 6](https://user-images.githubusercontent.com/17121385/137690910-ed54fcf0-b7e6-4cb0-b0be-5699ec128e80.jpg)
![Layer 6_thumbnail](https://user-images.githubusercontent.com/17121385/137690912-51ea4740-94a4-4c76-b067-63f89de9d533.jpg)
![Layer 7](https://user-images.githubusercontent.com/17121385/137690913-5f423ec7-87c8-4749-a4c8-c4c53b57459d.jpg)
![Layer 7_thumbnail](https://user-images.githubusercontent.com/17121385/137690916-feccf56e-9928-46e9-8ff8-7fbbdf7948ba.jpg)
![Layer 8](https://user-images.githubusercontent.com/17121385/137690919-50a94b98-6cbe-4f91-b631-2a5ff72215f3.jpg)
![Layer 8_thumbnail](https://user-images.githubusercontent.com/17121385/137690920-57942c7c-7f0c-48bf-afeb-1c2558948b7e.jpg)

**Description**
In HektAR, players take control of a small virtual farm to meet the needs of a growing community as sustainably as possible. Resources such as land, water and labor can be used to grow various crops as well as to buy and care for animals. The game deals with topics related to food production as well as weather events caused by climate change. Players learn about the demand for agricultural products, the relationship to climate, seasonality, soil degradation, water consumption, and the needs of animals. At the same time, as production increases, various phenomena related to climate change slowly begin to affect the environment. These phenomena include droughts and increased rainfall, which can affect the soil and water supply, as well as pests and diseases that can inhibit crop growth. These events force players to make tough choices that may influence their ability to provide for their community and/or contribute to further climate change events.

HektAR does not aim to compete with farm simulations such as the Farming Simulator, but tries to simplify the complexity of agricultural processes for a shorter play time. HektAR is also not a pure micromanagement game like Farmville, but facilitates thinking and decision-making processes regarding nutrition and production in order to present important real-world relationships in a playful way. With HektAR, one learns more about the individual ingredients of different meals and what they require in terms of production, but also about the challenges associated with limited resources and significant weather and climate events. HektAR is intended to be used in schools and museums to teach younger audiences about what choices they can make to help combat climate change by reducing waste and supporting sustainable agriculture.

**Team**
Jeremiah Diephuis
Georgi Kostov
Gabriel Mittermair

**Project partners**
Project partners are Climate Alliance Austria, the Austrian Museum of Society and Economy and the Upper Austria University of Applied Sciences (Playful Interactive Environments research group). The EAT Toolbox was funded by the Federal Ministry of Agriculture, Regions and Tourism and the European Union as part of the Austrian Rural Development Program 2014- 2020

**Comment by hochleitner** [comment]
Project details and images were added in bc96c40b7e08e16d9ef2558a53440390129e5d7d.

If you prefer a different order of the images or when the video's ready, just drop a comment here.

**Comment by hochleitner** [comment]
Video and a few other minor updates have been added in 05f74b030b4a656b10ac144af3fc6e8a2dfb3ce8.

I'm closing this issue.
